services:
  postgres:
    image: postgres:latest
    container_name: healthchain-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: healthchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "healthchain@team"
    ports:
      - "3000:5432"
    volumes:
      - healthchain_pg_data:/var/lib/postgresql/data
    networks:
      - healthchain_network

volumes:
  healthchain_pg_data:

networks:
  healthchain_network:
    driver: bridge
