spring:
  application:
    name: cardano.healthchain
  server:
    port: ${PORT:8080}
  web:
    resources:
      add-mappings: false
  sql:
    initialization:
      mode: always
    init:
      mode: always
springdoc:
  swagger-ui:
    enabled: true