spring:
  datasource:
    url: jdbc:postgresql://dpg-d5feptnpm1nc73dbn090-a/healthchain?user=healthchain_user&password=cWr7FJcKUKZzuN6fx21ZPgxJ1yp3QXfn
    #    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: healthchain_user
    password: cWr7FJcKUKZzuN6fx21ZPgxJ1yp3QXfn
  application:
    name: cardano.healthchain.production
  server:
    port: 8080
  web:
    resources:
      add-mappings: false
  sql:
    init:
      mode: always