spring:
  datasource:
    url: jdbc:${DATABASE_PRIVATE_URL}
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  application:
    name: cardano.healthchain.production
  server:
    port: ${PORT:8080}
  web:
    resources:
      add-mappings: false
  sql:
    init:
      mode: always